name: python-ddd-in-practise
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  # https://github.com/conda/conda/blob/main/tests/conda_env/support/advanced-pip/environment.yml
  - pip:
      - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
      - -r requirements.txt
